### PR TITLE
transpile third level sub-directories

### PR DESCRIPTION
**Pull request by LiranBri**
I'm not sure why, but `**/*.js` was not enough for me to transpile third level sub-directories. I had to add `**/**/*.js` for this to work.

### CODE REVIEW

**Comment by irvinlim** [comment]
Instead of exhaustively adding subdirectories, I used `cd src && babel . -d ../dist` instead (see #4).

**Comment by LiranBri** [comment]
cool. do you understand why `**/*.js` didn't work for nested directories?

**Comment by LiranBri** [comment]
by the way.. my solution didn't involve _exhaustively adding subdirectories_ .. it works recursively for any level of sub-directories

**Comment by irvinlim** [comment]
Hmm... I don't think your solution would work for fourth-level subdirectories if the original code didn't work for third-level subdirectories.

I believe the reason why it didn't work in the first place is glob expansion by the shell (see https://stackoverflow.com/a/34529436/2037090)... But using `.` as the current directory selector would work just fine as well.

**Comment by LiranBri** [comment]
with `**/**/*.js` it worked with 3 and 4 level ..

**Pull request closed without merging**
